### ISSUE TITLE
Remove item

### ISSUE THREAD

**Issue by maxvektor** [Money-Flow/Cash#9]
Add remove button to every item in list
Add  Confirm and cancel button

Confirm and cancel button only shown when remove button is pressed

**Given:** List with Items 
**When:** Press remove button
**Then:** Confirm and cancel button are shown

**Given:** Confirm and cancel button are shown
**When:** When the user press cancel
**Then:** Item is still presented, total is the same

**Given:** Confirm and cancel button are shown
**When:** When the user press confirm

**Then:** 
 - Item is removed from list,
 - total is recalculated

<img width="168" alt="Screen Shot 2020-03-24 at 1 22 12 PM" src="https://user-images.githubusercontent.com/5228778/77420359-92b33800-6dd2-11ea-972a-6b038bb98382.png">

**Comment by maxvektor** [comment]
Let's write e2e before closing

**Comment by anttibull** [comment]
Yes, thanks, I remember. This is an automatic moving card. Removed this setting. I will attach new tests to this issue in a new pull request.
